CREATE EXTENSION postgis;

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  hours text,
  description text,
  price_range text,
  location geography(point, 4326)
);


ALTER TABLE public.businesses 
    ADD COLUMN verification_source TEXT DEFAULT 'none',
    ADD COLUMN last_verified_at TIMESTAMP;


ALTER TABLE businesses ADD COLUMN raw_properties JSONB;

ALTER TABLE businesses ADD COLUMN last_updated TIMESTAMP DEFAULT NOW();
ALTER TABLE public.businesses ADD COLUMN average_rating NUMERIC;
ALTER TABLE businesses ADD COLUMN confidence_score FLOAT DEFAULT 0.5;
ALTER TABLE businesses ADD COLUMN opening_hours TEXT;


-- This assigns a realistic random rating to all businesses
UPDATE businesses 
SET average_rating = (random() * (5.0 - 3.5) + 3.5)::numeric(2,1)
WHERE average_rating IS NULL;

SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'businesses';



-- Check how many businesses are enriched
SELECT COUNT(*) FROM businesses WHERE description IS NOT NULL;

CREATE OR REPLACE FUNCTION get_nearby_businesses(user_lng FLOAT, user_lat FLOAT)
RETURNS TABLE (id BIGINT, name TEXT, distance_meters FLOAT) AS $$
BEGIN
  RETURN QUERY
  SELECT id, name, ST_Distance(location, ST_MakePoint(user_lng, user_lat)::geography) as dist
  FROM businesses
  WHERE ST_DWithin(location, ST_MakePoint(user_lng, user_lat)::geography, 1000)
  ORDER BY dist ASC;
END;
$$ LANGUAGE plpgsql;